/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmersonHint {
        "closable": boolean;
        "darkmode": boolean;
        "horizontal": boolean;
        "link": string;
        "vertical": boolean;
        "withimage": boolean;
        "withlink": boolean;
        "withtitle": boolean;
    }
    interface EmersonIcon {
        "name": string;
        "size": string;
    }
    interface MaterialInput {
        "label": string;
        "placeholder": string;
    }
}
declare global {
    interface HTMLEmersonHintElement extends Components.EmersonHint, HTMLStencilElement {
    }
    var HTMLEmersonHintElement: {
        prototype: HTMLEmersonHintElement;
        new (): HTMLEmersonHintElement;
    };
    interface HTMLEmersonIconElement extends Components.EmersonIcon, HTMLStencilElement {
    }
    var HTMLEmersonIconElement: {
        prototype: HTMLEmersonIconElement;
        new (): HTMLEmersonIconElement;
    };
    interface HTMLMaterialInputElement extends Components.MaterialInput, HTMLStencilElement {
    }
    var HTMLMaterialInputElement: {
        prototype: HTMLMaterialInputElement;
        new (): HTMLMaterialInputElement;
    };
    interface HTMLElementTagNameMap {
        "emerson-hint": HTMLEmersonHintElement;
        "emerson-icon": HTMLEmersonIconElement;
        "material-input": HTMLMaterialInputElement;
    }
}
declare namespace LocalJSX {
    interface EmersonHint {
        "closable"?: boolean;
        "darkmode"?: boolean;
        "horizontal"?: boolean;
        "link"?: string;
        "vertical"?: boolean;
        "withimage"?: boolean;
        "withlink"?: boolean;
        "withtitle"?: boolean;
    }
    interface EmersonIcon {
        "name"?: string;
        "size"?: string;
    }
    interface MaterialInput {
        "label"?: string;
        "placeholder"?: string;
    }
    interface IntrinsicElements {
        "emerson-hint": EmersonHint;
        "emerson-icon": EmersonIcon;
        "material-input": MaterialInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "emerson-hint": LocalJSX.EmersonHint & JSXBase.HTMLAttributes<HTMLEmersonHintElement>;
            "emerson-icon": LocalJSX.EmersonIcon & JSXBase.HTMLAttributes<HTMLEmersonIconElement>;
            "material-input": LocalJSX.MaterialInput & JSXBase.HTMLAttributes<HTMLMaterialInputElement>;
        }
    }
}
